import { Regulation, IncidentReport } from './types';

export const INITIAL_REGULATIONS: Regulation[] = [
  { id: 'sl-01', code: 'SL-01', description: 'Melanggar Lampu Merah', fine: 5000, jailTime: 0, category: 'satlantas' },
  { id: 'sl-02', code: 'SL-02', description: 'Melanggar Marka Jalan / Melawan Arus', fine: 2500, jailTime: 0, category: 'satlantas' },
  { id: 'sl-03', code: 'SL-03', description: 'Berkendara di Atas Trotoar / Area Pejalan Kaki', fine: 3500, jailTime: 0, category: 'satlantas' },
  { id: 'sl-04', code: 'SL-04', description: 'Melakukan Aksi Balapan Liar di Jalan Umum', fine: 15000, jailTime: 1, category: 'satlantas' },
  { id: 'sl-05', code: 'SL-05', description: 'Tidak Menggunakan Helm Standar / Sabuk Pengaman', fine: 1500, jailTime: 0, category: 'satlantas' },
  { id: 'sl-06', code: 'SL-06', description: 'Mengemudi Tanpa Surat Izin Mengemudi (SIM)', fine: 6000, jailTime: 0, category: 'satlantas' },
  { id: 'sl-07', code: 'SL-07', description: 'Menggunakan Plat Nomor Palsu / Tidak Terdaftar', fine: 10000, jailTime: 1, category: 'satlantas' },
  { id: 'sl-08', code: 'SL-08', description: 'Berkendara di Bawah Pengaruh Alkohol (DUI)', fine: 20000, jailTime: 2, category: 'satlantas' },
  { id: 'sl-09', code: 'SL-09', description: 'Melarikan Diri dari Pemeriksaan Razia Polantas', fine: 12000, jailTime: 1, category: 'satlantas' },
  { id: 'sl-10', code: 'SL-10', description: 'Menggunakan Kendaraan Modifikasi Ekstrim / Tidak Layak Jalan', fine: 4000, jailTime: 0, category: 'satlantas' },

  { id: 'pr-01', code: 'PR-01', description: 'Penghinaan Verbal Terhadap Petugas Kepolisian', fine: 5000, jailTime: 1, category: 'ringan' },
  { id: 'pr-02', code: 'PR-02', description: 'Tidak Membawa Kartu Identitas (KTP) saat Razia', fine: 2000, jailTime: 0, category: 'ringan' },
  { id: 'pr-03', code: 'PR-03', description: 'Membuang Sampah Sembarangan / Mengotori Fasilitas Kota', fine: 1000, jailTime: 0, category: 'ringan' },
  { id: 'pr-04', code: 'PR-04', description: 'Membuat Kebisingan di Area Pemukiman di Atas Jam Malam', fine: 3000, jailTime: 0, category: 'ringan' },
  { id: 'pr-05', code: 'PR-05', description: 'Menghalangi Akses Jalan Publik / Parkir Sembarangan', fine: 4000, jailTime: 0, category: 'ringan' },
  { id: 'pr-06', code: 'PR-06', description: 'Melakukan Perusakan Ringan pada Fasilitas Publik', fine: 6000, jailTime: 1, category: 'ringan' },
  { id: 'pr-07', code: 'PR-07', description: 'Merokok di Area Terlarang atau Dekat Pom Bensin', fine: 1500, jailTime: 0, category: 'ringan' },
  { id: 'pr-08', code: 'PR-08', description: 'Melakukan Provokasi Massa / Menyebarkan Berita Provokatif', fine: 8000, jailTime: 1, category: 'ringan' },
  { id: 'pr-09', code: 'PR-09', description: 'Pencemaran Nama Baik Warga Kota Melalui Media', fine: 7500, jailTime: 1, category: 'ringan' },
  { id: 'pr-10', code: 'PR-10', description: 'Memasuki Area Terlarang / Area Militer Tanpa Izin', fine: 5000, jailTime: 1, category: 'ringan' },

  { id: 'pm-01', code: 'PM-01', description: 'Pencarian / Pencurian Skala Kecil (Toko / Rumah)', fine: 10000, jailTime: 2, category: 'menengah' },
  { id: 'pm-02', code: 'PM-02', description: 'Penganiayaan Ringan Tanpa Senjata Terhadap Warga', fine: 12500, jailTime: 2, category: 'menengah' },
  { id: 'pm-03', code: 'PM-03', description: 'Penipuan Transaksi Publik / Jual Beli Bodong', fine: 15000, jailTime: 3, category: 'menengah' },
  { id: 'pm-04', code: 'PM-04', description: 'Membawa Senjata Tajam di Ruang Publik Tanpa Izin Kerja', fine: 18000, jailTime: 3, category: 'menengah' },
  { id: 'pm-05', code: 'PM-05', description: 'Mencoba Menyuap Petugas Kepolisian / Aparat Hukum', fine: 25000, jailTime: 4, category: 'menengah' },
  { id: 'pm-06', code: 'PM-06', description: 'Sengaja Merusak Properti Milik Warga Lain', fine: 14000, jailTime: 2, category: 'menengah' },
  { id: 'pm-07', code: 'PM-07', description: 'Pemerasan / Intimidasi Finansial Terhadap Korban', fine: 16500, jailTime: 3, category: 'menengah' },
  { id: 'pm-08', code: 'PM-08', description: 'Tabrak Lari yang Mengakibatkan Kerusakan Properti', fine: 22000, jailTime: 4, category: 'menengah' },
  { id: 'pm-09', code: 'PM-09', description: 'Kepemilikan dan Konsumsi Narkoba Dosis Kecil', fine: 20000, jailTime: 3, category: 'menengah' },
  { id: 'pm-10', code: 'PM-10', description: 'Sengaja Menghalangi Tugas Penyidikan / Menghapus Bukti', fine: 15000, jailTime: 2, category: 'menengah' },

  { id: 'pb-01', code: 'PB-01', description: 'Pembunuhan Berencana Terhadap Warga Sipil', fine: 100000, jailTime: 24, category: 'berat' },
  { id: 'pb-02', code: 'PB-02', description: 'Melakukan Perampokan Bank Utama / Toko Emas', fine: 80000, jailTime: 18, category: 'berat' },
  { id: 'pb-03', code: 'PB-03', description: 'Membawa atau Menyimpan Senjata Api Ilegal Kelas Militer', fine: 50000, jailTime: 12, category: 'berat' },
  { id: 'pb-04', code: 'PB-04', description: 'Penyerangan Bersenjata Terhadap Markas Kepolisian', fine: 75000, jailTime: 15, category: 'berat' },
  { id: 'pb-05', code: 'PB-05', description: 'Perdagangan / Menjadi Bandar Narkoba Skala Besar', fine: 90000, jailTime: 20, category: 'berat' },
  { id: 'pb-06', code: 'PB-06', description: 'Penyanderaan Warga Negara Menggunakan Senjata', fine: 60000, jailTime: 12, category: 'berat' },
  { id: 'pb-07', code: 'PB-07', description: 'Melakukan Makar Terhadap Instansi Pemerintah Kota', fine: 120000, jailTime: 30, category: 'berat' },
  { id: 'pb-08', code: 'PB-08', description: 'Aksi Terorisme / Peledakan Bom di Tempat Umum', fine: 150000, jailTime: 36, category: 'berat' },
  { id: 'pb-09', code: 'PB-09', description: 'Pembunuhan Terhadap Petugas Kepolisian saat Bertugas', fine: 120000, jailTime: 24, category: 'berat' },
  { id: 'pb-10', code: 'PB-10', description: 'Tindakan Korupsi Keuangan Daerah / Suap Skala Besar', fine: 85000, jailTime: 16, category: 'berat' },
];

export const INITIAL_REPORTS: IncidentReport[] = [
  {
    id: 'rep-1',
    timestamp: '2026-06-23T08:15:00-07:00',
    citizenName: 'Budi Santoso',
    articles: ['sl-01', 'sl-05', 'sl-06'],
    totalFine: 12500,
    totalJailTime: 0,
    type: 'lalu_lintas',
  },
  {
    id: 'rep-2',
    timestamp: '2026-06-22T21:40:00-07:00',
    citizenName: 'Michael Corleone',
    articles: ['pm-04', 'pm-05'],
    totalFine: 43000,
    totalJailTime: 7,
    type: 'kriminal',
  },
  {
    id: 'rep-3',
    timestamp: '2026-06-21T14:30:00-07:00',
    citizenName: 'Jessica Alva',
    articles: ['sl-08', 'sl-03'],
    totalFine: 23500,
    totalJailTime: 2,
    type: 'lalu_lintas',
  },
];
